TensorFlow HW1

In [8]:
import tensorflow as tf   

加載並準備MNIST 數據。將樣本從整數轉為浮點數

In [9]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

Sequential 通過堆疊層來構建模型。選擇優化器和損失函數進行訓練

In [10]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

對於每個範例，模型都會返回一個“ logits ”或“ log-odds ”分數向量，每個類別一個

In [11]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.37367967,  0.15195467,  0.04857412, -0.36793014, -0.47504196,
         0.20061626, -0.06226171, -0.13196301, -0.08266914,  0.17932865]],
      dtype=float32)

該tf.nn.softmax函數將這些 logits 轉換為每個類的“概率”

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

此損失等於真實類別的負對數概率：如果模型確定類別正確，則該損失為零。

這個未經訓練的模型給出的概率接近隨機（每個類為 1/10），因此初始損失應該接近-tf.math.log(1/10) ~= 2.3。

In [13]:
loss_fn(y_train[:1], predictions).numpy()

2.0370395

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

該Model.fit方法調整模型參數以最小化損失

In [15]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2961 - accuracy: 0.9133
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1423 - accuracy: 0.9572
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1044 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0890 - accuracy: 0.9720
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0756 - accuracy: 0.9754


該Model.evaluate方法通常在驗證或測試上檢查模型性能。

In [16]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0715 - accuracy: 0.9781


[0.07147174328565598, 0.9781000018119812]

現在，圖像分類器在此數據集上的訓練準確度約為 98%。
如果你想讓你的模型回傳一個概率，你可以使用訓練好的模型，並將 softmax 附加上去

In [17]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [18]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.42162715e-09, 5.92075278e-10, 2.27451346e-06, 3.09578195e-06,
        2.77563844e-12, 1.11181144e-08, 1.69778105e-13, 9.99993801e-01,
        8.69034400e-10, 7.78235972e-07],
       [6.88239554e-09, 9.18573642e-05, 9.99907613e-01, 4.67182161e-07,
        7.81037815e-15, 1.92929548e-08, 3.70264210e-08, 1.65637937e-11,
        2.02386747e-08, 1.06667754e-13],
       [1.52338646e-06, 9.98653650e-01, 1.29221808e-04, 4.31223953e-06,
        2.34399304e-05, 1.15910927e-06, 1.93323285e-05, 1.11071509e-03,
        5.59165856e-05, 6.75976082e-07],
       [9.99792993e-01, 1.03023385e-08, 7.28775285e-06, 3.69262465e-09,
        3.51561411e-08, 1.23442635e-06, 3.60532795e-05, 1.55705115e-04,
        8.76891171e-10, 6.72886927e-06],
       [6.06235290e-07, 8.59681819e-08, 1.51780987e-05, 8.63896261e-08,
        9.95624959e-01, 8.88053080e-07, 7.41086694e-07, 1.44337158e-04,
        3.85905565e-07, 4.21278318e-03]], dtype=float32)>